/home/sefi/scripts/apt_upgrade.sh
/home/sefi/scripts/configure_grub.sh
/home/sefi/scripts/configure_locale.sh
/home/sefi/scripts/configure_networking.sh
/home/sefi/scripts/configure_acpid.sh
/home/sefi/scripts/install_systemvm_packages.sh
/home/sefi/scripts/configure_conntrack.sh
/home/sefi/scripts/authorized_keys.sh
/home/sefi/scripts/configure_persistent_config.sh
/home/sefi/scripts/configure_login.sh
/home/sefi/cloud_scripts_shar_archive.sh
/home/sefi/scripts/configure_systemvm_services.sh
/home/sefi/scripts/cleanup.sh
/home/sefi/scripts/finalize.sh