#!/bin/bash
#------------------------------------------------------------------------------
# Licensed Materials (c) Copyright Log-On 2024, All Rights Reserved.
#------------------------------------------------------------------------------
# See usage for what this script does.

# Source script libraries as needed.
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
source "$DIR/lib/common.sh"
script_ended_ok=false
trap 'cleanup' EXIT

main() {
    init_vars "logon" "stop_cloudstack_agent_and_server" "$@"
    start_logging
    check_if_root
    stop_cs
    sleep 7
    clear_log_files
    do_cmd "systemctl start cloudstack-management.service"
    sleep 7
    do_cmd "systemctl start cloudstack-agent.service"
    sleep 7
    script_ended_ok=true
}

init_vars() {
    init_utils_vars $1 $2
}

clear_log_files() {
    for logfile in /var/log/cloudstack/management/management-server.log \
               /var/log/cloudstack/management/apilog.log \
               /var/log/cloudstack/agent/agent.log
    do
        if [ -f "$logfile" ]; then
            logMessage "--- Clearing $logfile"
            sudo truncate --size 0 $logfile
        fi
    done
}

main
