#!/bin/bash
#------------------------------------------------------------------------------
# Licensed Materials (c) Copyright Log-On 2024, All Rights Reserved.
#------------------------------------------------------------------------------
stop_cs
sleep 5
for logfile in /var/log/cloudstack/management/management-server.log \
               /var/log/cloudstack/management/apilog.log \
               /var/log/cloudstack/agent/agent.log; do
    if [ -f "$logfile" ]; then
        sudo touch $logfile
        sudo truncate --size 0 $logfile
    fi
done

sudo virsh net-start default
sudo virsh net-autostart default 
virsh net-list
sleep 5
sudo systemctl restart cloudstack-management.service
if systemctl list-unit-files | grep -q 'cloudstack-agent.service'; then
    sudo systemctl restart cloudstack-agent.service
fi
